# Generated by Django 5.2.6 on 2025-09-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='habitat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
