# Generated by Django 5.2.6 on 2025-10-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='description',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
