# Generated by Django 5.2.6 on 2025-10-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_alter_bird_description_alter_adventure_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Year Around', 'Year Around')], max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='bird',
            name='seasons',
        ),
        migrations.AddField(
            model_name='bird',
            name='seasons',
            field=models.ManyToManyField(blank=True, related_name='birds', to='species.season'),
        ),
    ]
