# Generated by Django 5.2.6 on 2025-10-25 16:02

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_season_remove_bird_seasons_bird_seasons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventure',
            old_name='name',
            new_name='cityName',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='description',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='location',
        ),
        migrations.AddField(
            model_name='adventure',
            name='country',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='adventure',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='adventure',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
