# Generated by Django 5.2.6 on 2025-12-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0004_rename_name_adventure_cityname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='habitats',
        ),
        migrations.AddField(
            model_name='bird',
            name='habitats',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
