# Generated by Django 5.2.6 on 2025-09-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0005_country_stateprovince'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StateProvince',
        ),
    ]
