# Generated by Django 5.2.6 on 2025-12-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0005_remove_bird_habitats_bird_habitats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
