# Generated by Django 5.2.6 on 2025-09-20 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0009_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='description',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='species.description'),
        ),
    ]
